# Generated by Django 6.0.4 on 2026-04-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bio_user_full_name_user_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="current_session_key",
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
