# Generated by Django 6.0.4 on 2026-04-10 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("children", "0002_child_gender_child_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="chat",
            name="child",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chats",
                to="children.child",
            ),
        ),
    ]
