# Generated by Django 6.0.4 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_message_ai_fields_aidraftreply"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="attachment",
            field=models.FileField(blank=True, null=True, upload_to="chat_attachments/"),
        ),
    ]
