# Generated by Django 6.0.4 on 2026-04-10 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("children", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="child",
            name="gender",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="child",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
