# Generated by Django 6.0.4 on 2026-04-21 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_alter_report_child"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="doctor_summary",
            field=models.TextField(blank=True),
        ),
    ]
